/**
 * Forge Write Capability tool.
 *
 * Creates a new tool extension scaffold in ~/.clawx/extensions/
 */

import { Type, type Static } from "@sinclair/typebox";
import type { AgentTool, AgentToolResult } from "@mariozechner/pi-agent-core";
import { join } from 'path';
import { mkdirSync, writeFileSync, existsSync } from 'fs';

const ForgeWriteCapabilitySchema = Type.Object({
  name: Type.String({ 
    description: "Tool name in kebab-case (e.g., 'medical-classifier', 'image-captioner')" 
  }),
  description: Type.String({ 
    description: "What the tool does" 
  }),
  modelId: Type.Optional(Type.String({ 
    description: "Optional: HuggingFace model ID used by this tool" 
  })),
  datasetId: Type.Optional(Type.String({ 
    description: "Optional: HuggingFace dataset ID used by this tool" 
  })),
  toolImplementation: Type.String({ 
    description: "TypeScript implementation code for tool.ts" 
  }),
  readmeContent: Type.String({ 
    description: "Markdown content for README.md (will have disclaimer added)" 
  }),
});

type ForgeWriteCapabilityInput = Static<typeof ForgeWriteCapabilitySchema>;

export interface ForgeWriteCapabilityDetails {
  name: string;
  path: string;
  filesCreated: string[];
}

export function createForgeWriteCapabilityTool(): AgentTool<typeof ForgeWriteCapabilitySchema, ForgeWriteCapabilityDetails> {
  return {
    name: "forge_write_capability",
    label: "Forge Write Capability",
    description:
      "Create a new tool extension scaffold in ~/.clawx/extensions/. " +
      "Generates capability.json, tool.ts, and README.md with scaffold disclaimer.",
    parameters: ForgeWriteCapabilitySchema,
    async execute(
      _toolCallId: string,
      params: ForgeWriteCapabilityInput,
    ): Promise<AgentToolResult<ForgeWriteCapabilityDetails>> {
      try {
        // Validate name (kebab-case)
        if (!/^[a-z0-9]+(-[a-z0-9]+)*$/.test(params.name)) {
          return {
            content: [{ type: "text", text: `Invalid tool name: "${params.name}". Must be kebab-case (lowercase letters, numbers, hyphens).` }],
            details: {
              name: params.name,
              path: "",
              filesCreated: [],
            },
          };
        }

        // Determine home directory
        const homeDir = process.env.HOME || process.env.USERPROFILE || '.';
        const extensionsDir = join(homeDir, '.clawx', 'extensions');
        const toolDir = join(extensionsDir, params.name);

        // Check if already exists
        if (existsSync(toolDir)) {
          return {
            content: [{ type: "text", text: `Extension "${params.name}" already exists at ${toolDir}` }],
            details: {
              name: params.name,
              path: toolDir,
              filesCreated: [],
            },
          };
        }

        // Create directories
        mkdirSync(extensionsDir, { recursive: true });
        mkdirSync(toolDir, { recursive: true });

        // Generate ID
        const id = `ext_${Math.random().toString(36).substring(2, 8)}`;

        // 1. Create capability.json
        const capabilityJson = {
          id,
          name: params.name,
          type: "tool" as const,
          description: params.description,
          version: "1.0.0",
          createdAt: new Date().toISOString(),
          enabled: false,
          tags: params.modelId ? ["model-based"] : params.datasetId ? ["dataset-based"] : [],
        };

        const capabilityPath = join(toolDir, 'capability.json');
        writeFileSync(capabilityPath, JSON.stringify(capabilityJson, null, 2));

        // 2. Create tool.ts
        const toolPath = join(toolDir, 'tool.ts');
        writeFileSync(toolPath, params.toolImplementation);

        // 3. Create README.md with disclaimer
        const disclaimer = `> **Forge-generated extension scaffold**
> 
> This extension was generated by Clawx Forge. It is not active in Clawx yet.
> 
> **Status**: Scaffold only — not loaded into Clawx runtime
> **Next steps**: Review the code, iterate as needed, then manually integrate
> **Auto-loading**: Not supported in this version of Forge
>
> ---
>
`;

        const readmePath = join(toolDir, 'README.md');
        writeFileSync(readmePath, disclaimer + params.readmeContent);

        const filesCreated = ['capability.json', 'tool.ts', 'README.md'];
        const text = `✅ Extension "${params.name}" created successfully!\n\n` +
              `Location: ${toolDir}\n` +
              `Files created:\n` +
              `  • capability.json (manifest)\n` +
              `  • tool.ts (implementation)\n` +
              `  • README.md (instructions)\n\n` +
              `**Important**: This is a scaffold only. The tool is not active in Clawx.\n` +
              `Review the code in ${toolDir} and integrate manually when ready.`;

        return {
          content: [{ type: "text", text }],
          details: {
            name: params.name,
            path: toolDir,
            filesCreated,
          },
        };
      } catch (error) {
        return {
          content: [{ type: "text", text: `Failed to create extension: ${error instanceof Error ? error.message : String(error)}` }],
          details: {
            name: params.name,
            path: "",
            filesCreated: [],
          },
        };
      }
    },
  };
}